version: '2.3'

services:

  esearch:
    image: ${DOCKER_REPOSITOR}/hzgc/elasticsearch:6.5.1
    container_name: esearch
    restart: always
    environment:
    - discovery.type=single-node
    - node.name=${DOCKER_HOST_NAME}
    - network.host=${DOCKER_HOST_IP}
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    hostname: esearch
    privileged: true
    network_mode: "host"
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ${DOCKER_HOME}/es/data:/usr/share/elasticsearch/data

  zookeeper:
    image: ${DOCKER_REPOSITOR}/hzgc/zookeeper:3.4.10
    container_name: zookeeper
    restart: always
    hostname: zookeeper
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    volumes:
    - ${DOCKER_HOME}/zookeeper/data:/data
    - ${DOCKER_HOME}/zookeeper/datalog:/datalog

  compare:
    image: ${DOCKER_REPOSITOR}/hzgc/compare:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    container_name: compare
    restart: always
    runtime: nvidia
    environment:
    - ZOOKEEPER_HOST=${ZK_HOST}:2181
    - ES_HOST=${ES_HOST}:9300
    network_mode: "host"
    volumes:
    - /persondir:/persondir
    - ${DOCKER_HOME}/compare/log:/log

  compareservice-0:
    image: ${DOCKER_REPOSITOR}/hzgc/compare-static:${VERSION}
    depends_on:
      - zookeeper
      - esearch
    container_name: compare-0
    restart: always
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - SERVICE_ID=0
    network_mode: "host"
    volumes:
      - /data/static/log:/facecompare/log
      - /data/static/data:/facecompare/matedata
      - /data/static/conf:/facecompare/conf

  compareservice-1:
    image: ${DOCKER_REPOSITOR}/hzgc/compare-static:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    container_name: compare-1
    restart: always
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - SERVICE_ID=1
    network_mode: "host"
    volumes:
    - /data/static/log:/facecompare/log
    - /data/static/data:/facecompare/matedata
    - /data/static/conf:/facecompare/conf

  compareservice-2:
    image: ${DOCKER_REPOSITOR}/hzgc/compare-static:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    container_name: compare-2
    restart: always
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - SERVICE_ID=2
    network_mode: "host"
    volumes:
    - /data/static/log:/facecompare/log
    - /data/static/data:/facecompare/matedata
    - /data/static/conf:/facecompare/conf

  compareservice-3:
    image: ${DOCKER_REPOSITOR}/hzgc/compare-static:${VERSION}
    depends_on:
    - zookeeper
    - esearch
    container_name: compare-3
    restart: always
    privileged: true
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - SERVICE_ID=3
    network_mode: "host"
    volumes:
    - /data/static/log:/facecompare/log
    - /data/static/data:/facecompare/matedata
    - /data/static/conf:/facecompare/conf

  vueweb:
    image: ${DOCKER_REPOSITOR}/gosun/spirieyeweb-tool:1.0.0-SNAPSHOT
    container_name: vueweb
    depends_on:
    - compare
    restart: always
    network_mode: "host"
    extra_hosts:
    - "gateway:${ZK_HOST}"
    volumes:
    - ${DOCKER_HOME}/mnt/web:/web

